version: "3.9"

name: myapi

services:
  api:
    build:
      context: ./auth
      dockerfile: Dockerfile
    # depends_on:
    #     - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    networks:
      - my-api-net
    volumes:
      - ./auth:/code  # Mount the auth directory to /code in the container 
#       Why Use Both?
# In your current setup:
#   The COPY ensures the image can run standalone and has all files
#       The volume mount enables hot reloading during development - when you edit files on your host machine, the changes are immediately available in the container

#   postgres_db:
#     image: postgres:latest  # Use the official PostgreSQL image
#     restart: always
#     container_name: PostgresCont
#     environment:
#         - POSTGRES_USER=ziakhan
#         - POSTGRES_PASSWORD=my_password
#         - POSTGRES_DB=mydatabase
#     ports:
#         - '5433:5432'
#     volumes:
#         - postgres_db:/var/lib/postgresql/data
#     networks:
#       - my-api-net

# volumes:
#   postgres_db:
#     driver: local

networks:
  my-api-net:  # Define the custom network